---
- name: Check if catalina_base needs be created
  stat: 
    path: "{{catalina_base}}/conf/Catalina/localhost"
  register: catalina_base_dir
  
- name: Create catalina_base
  file:
    path: "{{directories}}"
    state: directory
    owner: "{{tomcat_instance}}"
    group: "{{tomcat_instance}}"
  with_items: 
    - "{{catalina_base}}/conf/Catalina/localhost"
    - "{{catalina_base}}/bin"
    - "{{catalina_base}}/lib"
    - "{{catalina_base}}/logs"
    - "{{catalina_base}}/temp"
    - "{{catalina_base}}/webapps"
  when: catalina_base_dir.stat.exists == False
  loop_control:
    loop_var: directories
    label: "{{directories}}"

- name: "Extract Files {{catalina_base}}/conf"  
  unarchive: 
    src: "{{ tomcat_dwnldurl }}"
    remote_src: True
    dest: "{{catalina_base}}"
    owner: "{{tomcat_instance}}"
    group: "{{tomcat_instance}}"
    creates: "{{catalina_base}}/conf/server.xml"
    extra_opts: 
    - "{{catalina_version_dir}}/conf"
    - "--strip-components=1"
