--- 
- name: "Ensure group {{tomcat_instance}} exists"
  group:
    name: "{{tomcat_instance}}"
    state: present
    
- name: "Ensure user {{tomcat_instance}} exists"
  user:
    name: "{{tomcat_instance}}"
    comment: "{{tomcat_instance}} User"
    group: "{{tomcat_instance}}"
    groups: "{{tomcat_group}}"
    state: present 
 
