---
- name: Test Catalina
  shell: "java -cp {{catalina_home}}/lib/catalina.jar org.apache.catalina.util.ServerInfo"
  register: test_catalina_result
  changed_when: test_catalina_result.stdout_lines is not search('Apache Tomcat')

- debug:
    msg: 
      - "{{test_catalina_result.stdout_lines[0]}} / {{test_catalina_result.stdout_lines[6]}}"

