---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-centos8-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
    pre_build_image: true
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
